pdf:
	rm -rf ./output
	mkdir ./output
	pandoc --output output/dev_team_ru.pdf dev_team_ru.md --pdf-engine=xelatex
	pandoc --output output/domain_expert_accounting_ru.pdf domain_expert_accounting_ru.md --pdf-engine=xelatex
	pandoc --output output/domain_expert_general_ru.pdf domain_expert_general_ru.md --pdf-engine=xelatex
	pandoc --output output/domain_expert_online_ru.pdf domain_expert_online_ru.md --pdf-engine=xelatex
